comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        informational: true
        threshold: 1%
      patch: false
    patch: false