name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read
jobs:
  compile-with-bazel:
    runs-on: [self-hosted, trpc-cpp-ci]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile
      run: |
           ./clean.sh
           bazel test //trpc/...
  compile-with-cmake:
    runs-on: [self-hosted, trpc-cpp-ci]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Make
      run: |
           mkdir build
           cd build
           cmake ..
           make -j8
