name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read
jobs:
  compile-with-bazel:
    runs-on: [self-hosted, trpc-cpp-ci]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: |
           ./clean.sh
           bazel coverage //trpc/... --coverage_report_generator="@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main" --combined_report=lcov --nocache_test_results
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: bazel-out/_coverage/_coverage_report.dat
    - name: Run Examples
      run: ./run_examples.sh
  compile-with-cmake:
    runs-on: [self-hosted, trpc-cpp-ci]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Make
      run: |
           mkdir build
           cd build
           cmake ..
           make -j8
    - name: Run Examples
      run: ./run_examples_cmake.sh
